#!/bin/sh
printenv

echo "--------------------------------------------"
echo "Current commit: " $(git rev-parse HEAD)
echo "Previous commit: " $(git rev-parse HEAD^1)

COFFEE=./node_modules/.bin/coffee
UGLIFY=./node_modules/.bin/uglifyjs

# Was unsure where to place these since putting them in build/ is too late.
npm install coffee-script@1.8.0
npm install uglify-js@2.6.1

# Find the two commits to compare against: [START-1 ... END]
# END_COMMIT=$(git rev-parse HEAD)

# Find the commit to start from
if [ ${TRAVIS_PULL_REQUEST} != "false" ]
then
  # Testing a whole Pull Request.
  # This means the current commit is a new one with the branch merged into the PR destination.
  START_COMMIT=$(git rev-parse HEAD^1)
elif [ -z ${TRAVIS_COMMIT_RANGE} ]
then
  # No commit range specified. So this must be a new branch with 1 commit
  START_COMMIT=$(git rev-parse HEAD^1)
else
  START_COMMIT=$(echo ${TRAVIS_COMMIT_RANGE} | sed 's/\([a-z0-9\^]*\).*/\1/')
fi

echo "START_COMMIT=${START_COMMIT}"
echo "END_COMMIT=${END_COMMIT}"

# No need to check out since it is already checked out
# git checkout -q ${END_COMMIT}

cat $(find ./src -name "*.coffee") | ${COFFEE} --compile --stdio | ${UGLIFY} --beautify > .ci-cache-this.txt


# Check out the version *just before* the testing range
git checkout -q ${START_COMMIT}

cat $(find ./src -name "*.coffee") | ${COFFEE} --compile --stdio | ${UGLIFY} --beautify > .ci-cache-previous.txt



diff ./.ci-cache-previous.txt ./.ci-cache-this.txt > /dev/null

if [ $? -eq 0 ]
then
  echo "Just a documentation change. No need to run tests"
else
  echo "Code changed. Running tests"
  script/cibuild
fi
